resource_types:
- name: copr
  type: docker-image
  source:
    repository: quay.io/ahoi/concourse-copr-resource

resources:
- name: git-clone-resource
  type: git
  source:
    branch: master
    uri: https://github.com/thejambavan/systemcloud

- name: git-tag-resource
  type: git
  source:
    tag_filter: "v[0-9]*"
    branch: master
    uri: https://github.com/thejambavan/systemcloud

- name: git-ci
  type: git
  source:
    branch: master
    uri: https://github.com/thejambavan/systemcloud
    paths:
    - .concourse/*
    - .concourse/**/*
    - .concourse/centos/*
    - .concourse/ubuntu/*
    - .concourse/debian/*

- name: rpm-release
  type: s3
  source:
    endpoint: https://cdn.mb1.unipart.io
    bucket: systemcloud-rc
    regexp: (.*).rpm
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret-key))

- name: systemcloud-test-centos
  type: docker-image
  source:
    repository: centos
#    username: ((quay-ratpoison-username))
#    password: ((quay-ratpoison-password))
#    max_concurrent_downloads: 2
#    max_concurrent_uploads: 2


groups:
- name: release
  jobs:
  - build-pkg-rpm-release
- name: master
  jobs:
  - build-pkg-rpm
- name: env
  jobs:
  - oci-centos

jobs:
  - name: oci-centos
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: git-ci
      trigger: true
    - task: gen-container
      image: systemcloud-test-centos
      config:
        platform: linux
        inputs:
        - name: git-ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv .concourse/centos/Dockerfile ../copycat/
            cp -rfv .concourse/centos/pkg.lst ../copycat/
          dir: git-ci
  - name: build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: systemcloud-test-centos
        trigger: true
      - get: git-clone-resource
        trigger: true
    - task: create-rpm
      timeout: 15m
      image: systemcloud-test-centos
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: srpm
        - name: rpm
        run:
          path: ./.concourse/centos/buildrpm.sh
          args: [ .. ]
          dir: git-clone-resource

  - name: build-pkg-rpm-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: systemcloud-test-centos
        trigger: true
      - get: git-tag-resource
        trigger: true

    - task: create-rpm
      timeout: 15m
      image: systemcloud-test-centos
      config:
        platform: linux
        inputs:
        - name: git-tag-resource
        outputs:
        - name: srpm
        - name: rpm
        run:
          #path: ./.concourse/centos/buildrpm.sh
          path: /usr/bin/find
          #args: [ .. ]
          dir: git-tag-resource

    - put: rpm-release
      params:
        file: rpm/systemcloud*.rpm
        acl: public-read
