resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr
- name: copr
  type: docker-image
  source:
    repository: quay.io/ahoi/concourse-copr-resource

resources:
- name: git-clone-resource
  type: git
  source:
    branch: master
    uri: https://github.com/unipartdigital/systemcloud

- name: git-ci
  type: git
  source:
    branch: master
    uri: https://github.com/drahnr/systemcloud.git
    paths:
    - .concourse/*
    - .concourse/**/*
    - .concourse/fedora/*
    - .concourse/ubuntu/*

- name: rpm-release
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: systemcloud-rc
    regexp: (.*).rpm
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

- name: rpm-drop
  type: s3
  source:
    endpoint: https://minio.spearow.io
    bucket: systemcloud-drop
    regexp: (.*).rpm
    access_key_id: ((minio-access-key))
    secret_access_key: ((minio-secret-key))

groups:
- name: release
  jobs:
  - build-pkg-rpm-release
  - make-release
- name: master
  jobs:
  - build-pkg-rpm
    #  - compile
- name: env
  jobs:
  - oci-fedora

jobs:
  - name: oci-fedora
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: systemcloud-test-fedora
    - get: git-ci
      trigger: true

    - task: gen-container
      image: systemcloud-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv .concourse/fedora/Dockerfile ../copycat/
            cp -rfv .concourse/fedora/pkg.lst ../copycat/
          dir: git-ci

    - put: systemcloud-test-fedora
      params:
        build: copycat
        tag_as_latest: true


  - name: oci-ubuntu
    serial_groups: [constructors]
    build_logs_to_retain: 2
    plan:
    - get: systemcloud-test-ubuntu
    - get: git-ci
      trigger: true

    - task: gen-container
      image: systemcloud-test-ubuntu
      config:
        platform: linux
        inputs:
        - name: git-ci
        outputs:
        - name: copycat
        run:
          path: sh
          args:
          - -exc
          - |
            cp -rfv .concourse/ubuntu/Dockerfile ../copycat/
            cp -rfv .concourse/ubuntu/pkg.lst ../copycat/
          dir: git-ci

    - put: systemcloud-test-ubuntu
      params:
        build: copycat
        tag_as_latest: true


  - name: pr-validate
    build_logs_to_retain: 20
    public: true
    plan:
    - in_parallel:
      - get: systemcloud-test-fedora
        trigger: true
      - get: systemcloud-test-ubuntu
        trigger: true
      - get: git-pull-request-resource
        trigger: true
    - in_parallel:
      - task: compile
        timeout: 5m
        image: systemcloud-test-fedora
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          run:
            path: sh
            args:
            - -exc
            - |
              ./waf configure build --debug --prefix=/tmp install
              ./build/test/microtests
            dir: "git-pull-request-resource"

      - task: create-rpm
        timeout: 15m
        image: systemcloud-test-fedora
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          run:
            path: .concourse/fedora/buildrpm.sh
            dir: git-pull-request-resource

      - task: create-deb
        timeout: 15m
        image: systemcloud-test-ubuntu
        config:
          platform: linux
          inputs:
          - name: git-pull-request-resource
          run:
            path: debuild
            args: ["-i", "-us", "-uc", "-b"]
            dir: git-pull-request-resource


      on_success:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: success

      on_failure:
        put: git-pull-request-resource
        params:
          path: git-pull-request-resource
          status: failure

  - name: compile
    build_logs_to_retain: 10
    public: true
    plan:
    - in_parallel:
      - get: systemcloud-test-fedora
        trigger: true
      - get: git-clone-resource
        trigger: true

    - put: source-drop
      params:
        file: dist/systemcloud-*.tar.xz
        acl: public-read

  - name: build-pkg-rpm
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: systemcloud-test-fedora
        trigger: true
      - get: git-clone-resource
        trigger: true
        passed: [compile]

    - task: create-rpm
      timeout: 15m
      image: systemcloud-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-clone-resource
        outputs:
        - name: srpm
        - name: rpm
        run:
          path: ./.concourse/fedora/buildrpm.sh
          args: [ .. ]
          dir: git-clone-resource

    - put: rpm-drop
      params:
        file: rpm/systemcloud*.rpm
        acl: public-read

  - name: build-pkg-rpm-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: systemcloud-test-fedora
        trigger: true
      - get: git-tag-resource
        trigger: true

    - task: create-rpm
      timeout: 15m
      image: systemcloud-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-tag-resource
        outputs:
        - name: srpm
        - name: rpm
        run:
          path: ./.concourse/fedora/buildrpm.sh
          args: [ .. ]
          dir: git-tag-resource

    - put: rpm-release
      params:
        file: rpm/systemcloud*.rpm
        acl: public-read

    - put: copr
      resource: copr-resource
      params:
        rpmbuild_dir: "srpm"
        chroots: ["fedora-rawhide-x86_64", "fedora-29-x86_64", "fedora-28-x86_64", "fedora-27-x86_64"]
        enable_net: false
        max_n_bytes: 250000000
        project_id: 825
        regex: ".*systemcloud-.*\\.src\\.rpm$"

    - name: make-release
    build_logs_to_retain: 5
    public: true
    plan:
    - in_parallel:
      - get: git-tag-resource
        passed: [build-pkg-rpm-release]
        trigger: true
      - get: systemcloud-test-fedora
      - get: rpm-release
        passed: [build-pkg-rpm-release]
    - task: tag2file
      timeout: 5m
      image: systemcloud-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-tag-resource
        - name: rpm-release
        outputs:
        - name: release-info
        run:
          path: sh
          args:
          - -exc
          - |
            git rev-parse HEAD > ../release-info/COMMITISH
            ./waf version
            cat VERSION > ../release-info/TAG
            echo "systemcloud" > ../release-info/NAME
            echo "Yet another release" > ../release-info/BODY
          dir: git-tag-resource
    - put: gh-release
      params:
        tag_prefix: v
        name: release-info/NAME
        tag: release-info/TAG
        body: release-info/BODY
        commitish: release-info/COMMITISH
        globs:
        - rpm-release/systemcloud-*.rpm
      
