#!/usr/bin/python

"""Check freshness of a file"""

import argparse
import os
import sys
import time

parser = argparse.ArgumentParser(description="Check file freshness")
parser.add_argument('-m', '--max-age', type=int, default=30,
                    help="Maximum age (in seconds)")
parser.add_argument('file')
args = parser.parse_args()

try:
    st = os.stat(args.file)
except OSError:
    sys.stderr.write("Flag file %s is missing\n" % args.file)
    sys.stderr.write("This service should be started via systemcloud\n")
    sys.exit(2)

now = time.time()
age = (now - st.st_mtime)
if age > args.max_age:
    sys.stderr.write("Flag file %s is more than %d seconds old\n" %
                     (args.file, args.max_age))
    sys.stderr.write("This service should be started via systemcloud\n")
    sys.exit(1)

sys.exit(0)
